puts "Seeding default deck..."

deck = Deck.find_or_create_by!(name: "Base Deck") do |d|
  d.public = true
end

PROMPTS = [
  "Why did the party end early?",
  "What's the secret ingredient in grandma's cookies?",
  "What do you find in a pirate's treasure chest?",
  "My therapist says I need to stop thinking about ___.",
  "The real reason Santa Claus only works one day a year: ___.",
  "New scientific study: people who eat ___ live longer.",
  "What did the detective find at the crime scene?",
  "Why was the teacher sent home from school?",
  "What's inside Pandora's Box?",
  "The #1 most Googled phrase last year: ___.",
  "What's my guilty pleasure?",
  "During the zombie apocalypse, what is most useful?",
  "What keeps me up at night?",
  "___ — the musical.",
  "How do I get rid of a dead body?",
  "The next hot startup idea: ___.",
  "What do hipsters put in their coffee?",
  "What did the president forget to mention in the State of the Union?",
  "What's making the cat angry?",
  "Rejected slogans for ___.",
  "In a post-apocalyptic world, what becomes the new currency?",
  "What does Elon Musk dream about?",
  "What ruined my childhood?",
  "What's the most British thing possible?",
  "What is Batman's true weakness?",
  "The doctor prescribed ___ for my condition.",
  "What did the horoscope say this week?",
  "Life hack: never leave home without ___.",
  "What did I bring to show-and-tell?",
  "What's the worst part about time travel?",
  "Step 1: ___. Step 2: ???. Step 3: Profit.",
  "What does this country need more of?",
  "Coming this fall: ___ vs. ___.",
  "The cure for sadness: ___.",
  "What is the most powerful thing in the universe?",
  "What's in my search history that I can't explain?",
  "My New Year's resolution: more ___.",
  "What are my parents hiding from me?",
  "The theme song of my life: ___.",
  "What do cats actually think about all day?",
].freeze

RESPONSES = [
  "A horse with no name",
  "Passive-aggressive sticky notes",
  "Explaining cryptocurrency at dinner",
  "The entire works of Nickelback",
  "A firmly worded letter to the void",
  "Free-range gluten",
  "That one coworker who microwaves fish",
  "Sneezing into someone's salad",
  "Unironic cargo shorts",
  "A surprise dental appointment",
  "The concept of Mondays",
  "Naming your baby 'Wifi'",
  "Aggressively mediocre salsa",
  "A podcast about podcasts",
  "Falling asleep on public transit",
  "Extremely specific self-checkout errors",
  "Calling your professor 'mom'",
  "A LinkedIn influencer",
  "Running out of toilet paper at the worst possible moment",
  "The sound a wet sock makes",
  "Unsolicited life advice from a stranger",
  "Blaming it on Mercury retrograde",
  "Being on a cleanse",
  "Sentient bubble wrap",
  "Texting 'k'",
  "A passive-aggressive fruit basket",
  "The emotional support peacock",
  "Corporate synergy",
  "Getting personally attacked by a Roomba",
  "The last slice of pizza",
  "A ghost who only haunts IKEA",
  "Forgetting why you walked into a room",
  "A breakup via astrology chart",
  "Oat milk supremacy",
  "Mild disappointment",
  "Dad jokes at a funeral",
  "An NFT of someone's emotional damage",
  "Scheduling a meeting to schedule a meeting",
  "Explaining the plot of Inception",
  "The phrase per my last email",
  "A vegan vampire",
  "Googling symptoms at 2am",
  "A participation trophy",
  "The scent of a candle called Quiet Desperation",
  "Accidentally liking an old photo",
  "Hot dog water",
  "A certified organic crisis",
  "The audacity",
  "Going to HR",
  "A strongly worded tweet",
  "Total silence",
  "The Roman Empire",
  "A baby on a plane",
  "Being normal about celebrities",
  "Eating dinner at 4:30pm",
  "An all-caps email",
  "Whatever is in that gas station burrito",
  "Imposter syndrome",
  "A very confident wrong answer",
  "The entirety of Florida",
  "A firm handshake and no eye contact",
  "Explaining your diet to no one who asked",
  "Needing everyone to know you don't watch TV",
  "Referring to your pet as your emotional support",
  "Comparing everything to The Office",
  "A parking lot altercation",
  "Getting a we need to talk text from mom",
  "Air guitar at peak intensity",
  "Manifesting, but aggressively",
  "The 2007 internet",
  "A very small haunted house",
  "Putting pineapple on pizza on purpose",
  "Chronic main character syndrome",
].freeze

existing_prompts   = deck.cards.prompt.pluck(:content)
existing_responses = deck.cards.response.pluck(:content)

prompt_rows = PROMPTS.reject { |c| existing_prompts.include?(c) }.map { |c|
  { content: c, card_type: "prompt", deck_id: deck.id, status: "approved", pick_count: 1,
    created_at: Time.current, updated_at: Time.current }
}
response_rows = RESPONSES.reject { |c| existing_responses.include?(c) }.map { |c|
  { content: c, card_type: "response", deck_id: deck.id, status: "approved", pick_count: 1,
    created_at: Time.current, updated_at: Time.current }
}

Card.insert_all!(prompt_rows)   if prompt_rows.any?
Card.insert_all!(response_rows) if response_rows.any?

puts "  #{deck.cards.prompt.count} prompts, #{deck.cards.response.count} responses"
puts "Done."
