puts "Seeding default deck..."

deck = Deck.find_or_create_by!(name: "Base Deck") do |d|
  d.public = true
end

PROMPTS = [
  "Why did the sprint end with zero points delivered?",
  "What's the real reason the build is broken?",
  "What did the senior engineer leave out of the docs?",
  "My manager says I need to stop putting ___ in PRs.",
  "The root cause of the outage: ___.",
  "New engineering blog post: '10 Lessons Learned from ___'.",
  "What did the code reviewer find?",
  "Why was the standup cancelled?",
  "What's hiding in the legacy codebase?",
  "The #1 thing nobody reads: ___.",
  "What keeps engineers up at night?",
  "During a production incident, what is most useful?",
  "What's in the TODO comment from 2014?",
  "___ — the developer experience.",
  "How do you explain the tech debt to the CEO?",
  "The next billion-dollar SaaS idea: ___.",
  "What do PMs put in acceptance criteria?",
  "What did the all-hands forget to address?",
  "What's making the on-call engineer angry?",
  "Rejected names for the new microservice: ___.",
  "In a post-AGI world, what does the engineering team still do?",
  "What does the CTO dream about?",
  "What ruined the Q4 roadmap?",
  "What is the most passive-aggressive Slack message possible?",
  "What is the true enemy of shipping?",
  "The doctor recommended ___ for burnout.",
  "What did the exit interview reveal?",
  "Life hack: never deploy on ___.",
  "What did the intern push directly to main?",
  "What's the worst part about being on-call?",
  "Step 1: ___. Step 2: Rewrite it in Rust. Step 3: Profit.",
  "What does this codebase need more of?",
  "Coming this quarter: ___ vs. ___.",
  "The cure for a flaky test suite: ___.",
  "What is the most powerful abstraction in software?",
  "What's in my browser history I can't explain to my team?",
  "My OKR for next quarter: more ___.",
  "What is the engineering manager hiding?",
  "The theme song of the deployment pipeline: ___.",
  "What do developers actually think about during meetings?",
].freeze

RESPONSES = [
  "Cannot reproduce",
  "Reorg-ing again",
  "Works on my machine",
  "We'll fix it in the next sprint",
  "A 3,000-line pull request",
  "Undocumented behavior",
  "The 10x engineer who quit last month",
  "Rewriting everything in Go",
  "A Jira ticket with no description",
  "The free tier running out at 2am",
  "Pivoting to AI",
  "Naming a variable 'data2'",
  "An RFC that nobody will read",
  "Agile, but make it hurt",
  "Deploying on a Friday afternoon",
  "The GitHub Copilot suggestion that almost made it to prod",
  "Calling the police function 'doTheThing'",
  "A microservice for everything, including lunch orders",
  "Running out of AWS credits at demo day",
  "The sound a merge conflict makes",
  "Unsolicited architecture advice in the PR comments",
  "Blaming it on a race condition",
  "Being 'heads down' until the deadline passes",
  "Sentient technical debt",
  "Replying 'LGTM' without reading it",
  "A passive-aggressive inline comment",
  "The emotional support rubber duck",
  "Synergizing our core competencies",
  "Getting personally attacked by the linter",
  "The last engineer who touched this file",
  "A cron job that haunts production at 3am",
  "Forgetting to add the index",
  "A feature flag that was never cleaned up",
  "Null pointer supremacy",
  "Mild scope creep",
  "Stonks-only-go-up growth metrics",
  "An NFT of the incident postmortem",
  "Scheduling a meeting to discuss the meeting",
  "Explaining eventual consistency at dinner",
  "The phrase 'per my last Slack message'",
  "A senior engineer who only communicates in emojis",
  "Stack Overflow at 2am",
  "A gold-plated abstraction nobody asked for",
  "The smell of a codebase called Quiet Desperation",
  "Accidentally force-pushing to main",
  "Hot-patching production",
  "A certified organic memory leak",
  "The audacity of the cloud bill",
  "Going to the architecture review board",
  "A strongly worded commit message",
  "Total radio silence in the incident channel",
  "The concept of estimates",
  "A baby's first undefined behavior",
  "Being normal about tabs vs. spaces",
  "Pushing to prod at 4:30pm on Friday",
  "An all-caps Slack message from the CEO",
  "Whatever is in that 8-year-old migration",
  "Imposter syndrome at the senior engineer level",
  "A very confident wrong Stack Overflow answer",
  "The entirety of the JavaScript ecosystem",
  "A firm rejection from code review with no explanation",
  "Explaining your tech stack to no one who asked",
  "Needing everyone to know you use Neovim",
  "Referring to prod as your personal test environment",
  "Comparing everything to how we did it at Google",
  "A calendar that is somehow still double-booked",
  "Getting a 'we need to talk' Slack DM from your skip-level",
  "Air-quoting 'best practices' at peak intensity",
  "Manifesting a promotion cycle, aggressively",
  "The 2007 jQuery codebase",
  "A very small monolith",
  "Shipping the bug as a feature on purpose",
  "Chronic main character syndrome in the architecture diagram",
].freeze

existing = deck.cards.pluck(:content)

prompt_rows = PROMPTS.reject { |c| existing.include?(c) }.map { |c|
  { content: c, card_type: "prompt", deck_id: deck.id, status: "approved", pick_count: 1,
    created_at: Time.current, updated_at: Time.current }
}
response_rows = RESPONSES.reject { |c| existing.include?(c) }.map { |c|
  { content: c, card_type: "response", deck_id: deck.id, status: "approved", pick_count: 1,
    created_at: Time.current, updated_at: Time.current }
}

Card.insert_all!(prompt_rows)   if prompt_rows.any?
Card.insert_all!(response_rows) if response_rows.any?

puts "  #{deck.cards.prompt.count} prompts, #{deck.cards.response.count} responses"
puts "Done."
